"""
Pydantic data models for structured output validation.

Defines strict validation schemas for headline sentiment outputs, aggregated sentiment analysis,
and LLM-based trading recommendations.
"""

import re
from typing import List, Literal
from pydantic import BaseModel, Field, field_validator

# Allowed sentiment classifications
SentimentType = Literal["positive", "negative", "neutral"]
OverallSentimentType = Literal["POSITIVE", "NEGATIVE", "NEUTRAL"]
RecommendationType = Literal["BUY", "HOLD", "SELL"]


class HeadlineSentiment(BaseModel):
    """
    Validated sentiment model for a single financial news headline.
    """

    headline: str = Field(..., min_length=1, description="Financial news headline text.")
    sentiment: SentimentType = Field(..., description="Sentiment classification: positive, negative, or neutral.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence score bounded between 0.0 and 1.0.")
    brief_reason: str = Field(..., min_length=1, description="Brief justification for the sentiment classification.")

    @field_validator("headline", "brief_reason")
    @classmethod
    def check_non_empty_string(cls, val: str) -> str:
        """Ensure string fields contain non-whitespace characters."""
        if not val or not val.strip():
            raise ValueError("String field cannot be empty or whitespace only.")
        return val.strip()

    @field_validator("sentiment")
    @classmethod
    def normalize_sentiment_label(cls, val: str) -> str:
        """Normalize sentiment string to lowercase."""
        cleaned = str(val).strip().lower()
        if cleaned not in ("positive", "negative", "neutral"):
            raise ValueError("Sentiment must be 'positive', 'negative', or 'neutral'.")
        return cleaned


class AggregatedSentiment(BaseModel):
    """
    Aggregated sentiment summary model computed over a collection of headlines.
    """

    total_headlines: int = Field(..., ge=0, description="Total number of evaluated headlines.")
    positive_count: int = Field(..., ge=0, description="Number of positive headlines.")
    negative_count: int = Field(..., ge=0, description="Number of negative headlines.")
    neutral_count: int = Field(..., ge=0, description="Number of neutral headlines.")
    weighted_sentiment_score: float = Field(
        ..., ge=-1.0, le=1.0, description="Confidence-weighted aggregate sentiment score in [-1.0, 1.0]."
    )
    overall_label: OverallSentimentType = Field(..., description="Overall aggregate sentiment classification.")
    headline_results: List[HeadlineSentiment] = Field(
        default_factory=list, description="List of validated individual headline sentiment results."
    )


class TradingRecommendation(BaseModel):
    """
    Validated trading recommendation model generated by LLM reasoning.
    """

    recommendation: RecommendationType = Field(..., description="Trading recommendation action: BUY, HOLD, or SELL.")
    reasoning: str = Field(..., min_length=10, description="Evidence-based reasoning in 3 to 5 sentences.")

    @field_validator("recommendation")
    @classmethod
    def normalize_recommendation(cls, val: str) -> str:
        """Normalize recommendation action to uppercase."""
        cleaned = str(val).strip().upper()
        if cleaned not in ("BUY", "HOLD", "SELL"):
            raise ValueError("Recommendation must be strictly 'BUY', 'HOLD', or 'SELL'.")
        return cleaned

    @field_validator("reasoning")
    @classmethod
    def check_reasoning_sentences(cls, val: str) -> str:
        """Ensure reasoning text is a non-empty string and contains between 3 and 5 sentences."""
        cleaned = val.strip()
        if not cleaned:
            raise ValueError("Reasoning text cannot be empty.")

        # Split text into sentences using punctuation terminators (. ! ?)
        sentences = [s.strip() for s in re.split(r"[.!?]+", cleaned) if s.strip()]
        sentence_count = len(sentences)

        if sentence_count < 3 or sentence_count > 6:  # Allow slight tolerance up to 6
            raise ValueError(f"Reasoning must contain between 3 and 5 sentences (got {sentence_count}).")

        return cleaned
