# AI-ASSISTED: Gemini (gemini-3.6-flash), Prompt: 'Create task3_financial_agents/run_multi_demo.py to allow running the multi-agent workflow (Agent A -> DataBrief -> Agent B) from terminal with trace logs', Date: 2026-09-11
"""
Standalone Demonstration Script for Task 3B Multi-Agent Research System.

Run this script to watch Agent A (Data Analyst) collect quantitative metrics,
perform a structured DataBrief handoff, and Agent B (Research Writer) synthesize
the final report.

Usage:
    python run_multi_demo.py [TICKER]
Example:
    python run_multi_demo.py NVDA
"""

import sys
import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from src.workflows import run_multi_agent_research


def main():
    ticker = sys.argv[1].upper() if len(sys.argv) > 1 else "NVDA"

    print("=" * 85)
    print(f"🚀 RUNNING MULTI-AGENT RESEARCH SYSTEM (AGENT A -> HANDOFF -> AGENT B) FOR: {ticker}")
    print("=" * 85 + "\n")

    try:
        final_state = run_multi_agent_research(ticker=ticker)

        print("\n" + "=" * 85)
        print("🤝 STRUCTURED DATABRIEF HANDOFF PAYLOAD (GENERATED BY AGENT A FOR AGENT B)")
        print("=" * 85 + "\n")
        print(json.dumps(final_state.get("data_brief"), indent=2))

        print("\n" + "=" * 85)
        print("📄 FINAL SYNTHESIZED MULTI-AGENT EQUITY RESEARCH REPORT (PRODUCED BY AGENT B)")
        print("=" * 85 + "\n")
        print(final_state.get("final_report", "No report generated."))
        print("\n" + "=" * 85)
        print("✅ MULTI-AGENT RESEARCH WORKFLOW COMPLETED SUCCESSFULLY")
        print("=" * 85)

    except Exception as exc:
        print(f"\n❌ Execution Error: {exc}")


if __name__ == "__main__":
    main()
